export const newProducts = [
    {
        id: 'newproduct1',
        name: 'Áo Thun Gấu Nâu',
        thumbnail: '/general/aothungaunau.jpg',
        price: 139000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newproduct2',
        name: 'Áo Dây Mặt Trăng',
        thumbnail: '/general/aodaymattrang.jpg',
        price: 105000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newproduct3',
        name: 'Đầm Hoa Cột Nơ Eo',
        thumbnail: '/general/damhoa.jpg',
        price: 270000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newproduct4',
        name: 'Sơ Mi Kiểu',
        thumbnail: '/general/aosomikieu.jpg',
        price: 205000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newproduct5',
        name: 'Áo Khoác Len',
        thumbnail: '/general/aokhaclen.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const hotProducts = [
    {
        id: 'hotproduct1',
        name: 'Quần baggy',
        thumbnail: '/general/quanbaggy.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct2',
        name: 'Sơ mi cổ vest trái dứa',
        thumbnail: '/general/somicovest.jpg',
        price: 165000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct3',
        name: 'Wool Coats',
        thumbnail: '/general/woolcoats.jpg',
        price: 120000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct4',
        name: 'Cotton Baggy Trousers',
        thumbnail: '/general/cottonbaggy.jpg',
        price: 205000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'hotproduct5',
        name: 'Sơ mi truyền thống',
        thumbnail: '/general/somitruyenthong.jpg',
        price: 165000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const newImports = [
    {
        id: 'newimport1',
        name: 'Baggy Jeans',
        thumbnail: '/general/baggyjeans.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport2',
        name: 'Áo Khoác Len',
        thumbnail: '/general/aokhoaclen.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport3',
        name: 'Sơ Mi Caro Dệt Nổi',
        thumbnail: '/general/somicaro.jpg',
        price: 240000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newimport4',
        name: 'Linen Shirt',
        thumbnail: '/general/linenshirt.jpg',
        price: 195000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport5',
        name: 'Edging Jacket',
        thumbnail: '/general/edging.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const somis = [
    {
        id: '80',
        title: 'Áo Viral Top',
        price: 370000,
        thumbnail: '/public/ao-kieu/viraltop.jpg',
        category: 'ao-kieu',
        type: 'new',
        soldOut: false,
    },
    {
        id: '79',
        title: 'Áo Layla Basic',
        price: 360000,
        thumbnail: '/public/ao-kieu/layla-basic.jpg',
        category: 'ao-kieu',
        type: 'new',
        soldOut: false,
    },
    {
        id: '78',
        title: 'Áo Honey Top',
        price: 350000,
        thumbnail: '/public/ao-kieu/honeytop.jpg',
        category: 'ao-kieu',
        type: 'new',
        soldOut: false,
    },
    {
        id: '77',
        title: 'Áo Doll Cotton',
        price: 310000,
        thumbnail: '/public/ao-kieu/dollcotton.jpg',
        category: 'ao-kieu',
        type: 'new',
        soldOut: false,
    },
    {
        id: '76',
        title: 'Áo BabyDoll Dệt Nổi',
        price: 320000,
        thumbnail: '/public/ao-kieu/detnoi.jpg',
        category: 'ao-kieu',
        type: 'new',
        soldOut: false,
    },
]
